sudo: required
service:
  - docker

before_install:
  - docker build -t abhishek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishek/react-test npm test

after_success:
  - docker build -t abhishekgupta30/multi-client ./client
  - docker build -t abhishekgupta30/multi-nginx ./nginx
  - docker build -t abhishekgupta30/multi-server ./server
  - docker build -t abhishekgupta30/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push abhishekgupta30/multi-client
  - docker push abhishekgupta30/multi-nginx 
  - docker push abhishekgupta30/multi-server
  - docker push abhishekgupta30/multi-worker