sudo: required
service:
  - docker

before_install:
  - docker build -t abhishek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishek/react-test npm test

after_success:
  - docker build -t abhishekgupta30/multi-client ./client
  - docker build -t abhishekgupta30/multi-nginx ./nginx
  - docker build -t abhishekgupta30/multi-server ./server
  - docker build -t abhishekgupta30/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push abhishekgupta30/multi-client
  - docker push abhishekgupta30/multi-nginx 
  - docker push abhishekgupta30/multi-server
  - docker push abhishekgupta30/multi-worker

Deploy:
    provider: elasticbeanstalk
    region: 'ap-south-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-ap-south-1-277011773517'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY